#Podfile
use_frameworks!

## I use this to share pods between more targets whenever I need it
def sharedPods
    pod 'Alamofire', '~> 5.0.0.beta.5'
end

target 'CurrencyConverter' do
    sharedPods
end

